# Problem 1
### Matrix product is calculated manually



A=\begin{bmatrix} -1 & 2 & 3 \\ 4 & -5 & 6 \\ 7 & 8 & -9 \end{bmatrix},
B=\begin{bmatrix} 0 & 2 & 1 \\ 0 & 2 & -8 \\ 2 & 9 & -1 \end{bmatrix}


## **Calculation process**

**First: Inter-multiplication of every matrix element :**

\begin{bmatrix}
(-1*0)+(2*0)+(3*2)&(-1*2)+(2*2)+(3*9)&(-1*1)+(2*-8)+(3*-1)\\
(4*0)+(-5*0)+(6*2)&(4*2)+(-5*2)+(6*9)&(4*1)+(-5*-8)+(6*-1)\\
(7*0)+(8*0)+(-9*2)&(7*2)+(8*2)+(-9*9)&(7*1)+(8*-8)+(-9*-1)\\
\end{bmatrix},



**Then: Add each part of the matrix**

\begin{bmatrix}
(O+0+6)&(-2+4+27)&(-1-16-3)\\
(O+0+12)&(8-10+54)&(4+40-6)\\
(O+0-18)&(14+16-81)&(7-64+9)\\
\end{bmatrix},


**Result:**

\begin{pmatrix} 
6&29&-20\\
12&52&38\\
-18&-51&-48
\end{pmatrix}


# Problem 2
### Calculation by NumPy function

In [1]:
import   numpy   as  np
ndarray_A = np.array([[-1, 2, 3], [4, -5, 6], [7, 8, -9]])
ndarray_B = np.array([[0, 2, 1], [0, 2, -8], [2, 9, -1]])
ndarray_A_B = np.matmul(ndarray_A,ndarray_B)
print(ndarray_A_B)

[[  6  29 -20]
 [ 12  52  38]
 [-18 -51 -48]]


# Problem 3
### Implementation of calculation of a certain element

In [5]:
sum_matrix = (ndarray_A[1][0]*ndarray_B[0][1])+(ndarray_A[1][1]*ndarray_B[1][1])+(ndarray_A[1][2]*ndarray_B[2][1])
sum_matrix

52

# Problem 4
### Creating a function that performs matrix multiplication

In [2]:
def product_of_matrix(a, b):
    ndarray_A_B = np.empty([3,3])
    for row in range(a.shape[0]):
        for column in range(b.shape[1]):
            ndarray_A_B[row][column] = sum(a[row, :]*b[:, column])
    return ndarray_A_B
print(product_of_matrix(ndarray_A, ndarray_B))

[[  6.  29. -20.]
 [ 12.  52.  38.]
 [-18. -51. -48.]]


# Problem 5
### Judge the input whose calculation is not defined

In [6]:
import numpy as np

def product_of_matrix(matrix1, matrix2):
    if matrix1.shape[1] != matrix2.shape[0]:
        print("Error: Matrix dimensions are not compatible for multiplication.")
        return None
    return np.dot(matrix1, matrix2)

def perform_matrix_multiplication(matrix1, matrix2):
    result_matrix = product_of_matrix(matrix1, matrix2)
    
    if result_matrix is not None:
        print("Result of matrix multiplication:")
        print(result_matrix)

d_ndarray = np.array([[-1, 2, 3], [4, -5, 6]])
e_ndarray = np.array([[-9, 8, 7], [6, -5, 4]])

perform_matrix_multiplication(d_ndarray, e_ndarray)


Error: Matrix dimensions are not compatible for multiplication.


# Problem 6
### Transposition


In [12]:
f = d_ndarray.T
print(product_of_matrix(f, e_ndarray))

[[ 33 -28   9]
 [-48  41  -6]
 [  9  -6  45]]
